# Generated by Django 5.0.6 on 2026-05-05 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('lieu', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('duree', models.IntegerField()),
                ('capacite', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/')),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('devise', models.CharField(choices=[('MAD', 'MAD'), ('EUR', 'Euro'), ('USD', 'Dollar')], default='MAD', max_length=10)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorie.categorie')),
            ],
        ),
    ]
