# Generated by Django 5.0.6 on 2026-05-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('administrateur', 'Administrateur'), ('participant', 'Participant'), ('organisateur', 'Organisateur')], default='participant', max_length=20),
        ),
    ]
