# Generated by Django 5.0.6 on 2026-05-05 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Billet', '0001_initial'),
        ('Inscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='inscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billet', to='Inscription.inscription'),
        ),
    ]
