# Generated by Django 5.0.6 on 2026-05-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billet', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
    ]
